import express from 'express';

export type Res = express.Response
export type Req = express.Request

export enum ErrorCode {
  MALFORMED_PLAYER_NAME = 'MALFORMED_PLAYER_NAME',
  MOJANG_API_ERROR = 'MOJANG_API_ERROR',
  MOJANG_PLAYER_NOT_FOUND = 'MOJANG_PLAYER_NOT_FOUND',
  PLAYER_NOT_FOUND = 'PLAYER_NOT_FOUND',
  MALFORMED_UUID = 'MALFORMED_UUID',
  UUID_NOT_FOUND = 'UUID_NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  HYPIXEL_API_ERROR = 'HYPIXEL_API_ERROR',
  MALFORMED_DATA_FORMAT = 'MALFORMED_DATA_FORMAT',
  PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND',
  PLAYER_NOT_IN_PROFILE = 'PLAYER_NOT_IN_PROFILE',
}